#!/bin/bash
./pluto init blockworld.db
./pluto add blockworld.db "0" isa block
./pluto add blockworld.db "0" has color red
./pluto add blockworld.db "0" has size large
./pluto add blockworld.db "0" has location on table
./pluto add blockworld.db "0" has location behind "1"

./pluto add blockworld.db "1" isa cube
./pluto add blockworld.db "1" has size small
./pluto add blockworld.db "1" has color red
./pluto add blockworld.db "1" has location on table

./pluto add blockworld.db "2" isa pyramid
./pluto add blockworld.db "2" has color red
./pluto add blockworld.db "2" has size small
./pluto add blockworld.db "2" has location on "1"

./pluto add blockworld.db "4" isa block
./pluto add blockworld.db "4" has color blue
./pluto add blockworld.db "4" has size tall
./pluto add blockworld.db "4" has location on table

./pluto add blockworld.db "5" isa block
./pluto add blockworld.db "5" has color green
./pluto add blockworld.db "5" has location on table

./pluto add blockworld.db "6" isa block
./pluto add blockworld.db "6" has color green
./pluto add blockworld.db "6" has location on table
./pluto add blockworld.db "6" has location "in-front" "5"

./pluto add blockworld.db "7" isa box
./pluto add blockworld.db "7" has color white
./pluto add blockworld.db "7" has location on table

./pluto add blockworld.db "8" isa pyramid
./pluto add blockworld.db "8" has size tall
./pluto add blockworld.db "8" has location on "6"

./pluto add blockworld.db "9" isa pyramid
./pluto add blockworld.db "9" has size wide
./pluto add blockworld.db "9" has location "in" "7"
