#!/usr/bin/env python3
from database import Database

def main():
    db = Database()
    db.add('a has sides three')
    db.add('a has color green')
    db.get('three')
    db.get('green')
    db.get('has color')
    db.get('has sides')
    db.get('three')
    db.get('a')

if __name__ == '__main__':
    main()
