#!/usr/bin/env python3
from mdict import MultiDictionary

def main():
    mdict = MultiDictionary()

    mdict.ninsert('a has sides three')
    mdict.ninsert('a has color green')
    print(mdict.nmentions('three'))
    print(mdict.nmentions('green'))
    print(mdict.nmentions('has color'))
    print(mdict.nmentions('has sides'))
    print(mdict.nmentions('three'))
    print(mdict.nmentions('a'))

    '''
    mdict.ninsert('a b c d e')
    mdict.ninsert('a b c f e')

    print(mdict.reverse_lookup('e'))
    print(mdict.nmentions('a b'))
    print(mdict.nmentions('c d'))
    '''

if __name__ == '__main__':
    main()
